version: '3.8'
services:
  postgres:
    env_file:
      - ./.env.local
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      - POSTGRES_DB=dailyblow
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - '2223:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=${POSTGRES_USER} --dbname=dailyblow"
        ]
      interval: 20s
      timeout: 5s
      retries: 3
volumes:
  postgres: null
networks:
  outpost_network:
    external: true